name: 'Deaths Today Bot'

on:
  push:
  # schedule:
  #  - cron: '0 9 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --if-present
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Today's events" --allow-empty
          git push
