name: 'Send email'

on:
  # push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          persist-credentials: false
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install Dependencies
        run: npm install
      - run: npm run build --if-present
      - name: Send email
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          node sendgrid.js
